CREATE TABLE STATUS_TYPE (ST_ID CHAR(4) NOT NULL, ST_NAME CHAR(10) NOT NULL, PRIMARY KEY (ST_ID));
CREATE TABLE ZIP_CODE (ZC_CODE CHAR(12) NOT NULL, ZC_TOWN CHAR(80) NOT NULL, ZC_DIV CHAR(80) NOT NULL, PRIMARY KEY (ZC_CODE));
