FROM ubuntu:18.04

RUN apt update
RUN apt install -y make g++ libmysqlclient-dev curl wget
RUN apt install -y lsb-release wget software-properties-common gnupg
RUN apt install -y clang
RUN apt install -y llvm
RUN curl ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-2.3.12.tar.gz --output odbc.tar.gz
RUN tar -zxvf odbc.tar.gz
RUN cd unixODBC-2.3.12 && ./configure && make && make install
RUN apt install -y git
RUN git clone https://github.com/Percona-Lab/tpce-mysql
WORKDIR /tpce-mysql
RUN mkdir bin lib flat_out obj
WORKDIR /tpce-mysql/prj
RUN make

